Systems_Analysis_and_Design/Final_Project__File_Archive_over_Google_Drive/config/routes.rb
Rails.application.routes.draw do

  get 'user/:t_id' => 'user#show',as: :user_show
  
  get 'folder/new(/:f_id)' => 'folder#new',as: :folder_new

  get 'user/:t_id/:f_id' => 'folder#show'

  get 'file/new/:user_id/:f_id' => 'file_record#new',as: :file_new

  get 'folder/edit/:f_id' => 'folder#edit',as: :folder_edit
  
  patch 'folder/update/:f_id' => 'folder#update',as: :folder_update

  delete 'folder/destroy/:f_id' => 'folder#destroy',as: :folder_destroy

  post 'folder/create(/:f_id)' => 'folder#create',as: :folder_create

  post 'file/create(/:f_id)' => 'file_record#create',as: :file_create

  get 'user/:t_id/:f_id/file/:file_id' => 'file_record#show'

  delete 'user/:t_id/:f_id/file/:file_id/destroy' => 'file_record#destroy'

  post 'user/:t_id/:f_id/status/:status' => 'folder#change_status',as: :folder_change_status

  post 'user/:t_id/:f_id/file/:file_id/status/:status' => 'file_record#change_status',as: :file_record_change_status

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "home#index"

  match '*not_found', to: "home#index",via: [:*]

  

end

Systems_Analysis_and_Design/Final_Project__File_Archive_over_Google_Drive/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @folders = Folder.where(:parent_folder_id=>nil).where(:status=>:public).where.not(:user_id=>current_user.id)
      @folders = @folders + Folder.where(:parent_folder_id=>nil).where(:user_id=>current_user.id)
    else
      @folders = Folder.where(:parent_folder_id=>nil).where(:status=>:public)
    end
    @folders
  end

end

Systems_Analysis_and_Design/Final_Project__File_Archive_over_Google_Drive/app/helpers/home_helper.rb
module HomeHelper
end

Systems_Analysis_and_Design/Final_Project__File_Archive_over_Google_Drive/app/views/home/index.html.erb
  <div class="panel-body">
    <div class="dataTable_wrapper">
      <table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
          <tr>
            <th>名稱</th>
            <th>開課學期</th>
            <th>開課老師</th>
            <th>建立時間</th>
            <th>大小</th>
            <th>隱私</th>
            <th>動作</th>
          </tr>
        </thead>
        <tbody>
          <% @folders.each do |folder|%>
          <tr>
            <td><i class="fa fa-folder"></i>  <%= link_to folder.name, folder.url_string %></td>
            <td><%= folder.semester %></td>
            <td><%= link_to folder.user.name ,user_show_path(folder.user.id) %></td>
            <td><%= folder.created_at %></td>
            <td><i class="fa fa-times"></i></td>
            <td><%= folder.status_text %></td>
            <td class="center">
              <% if current_user && folder.user.id == current_user.id %>
              <%= link_to '刪除', folder_destroy_path(folder.id), :class=>"btn btn-outline btn-danger", method: :delete %>
              <%= link_to '編輯內容', folder_edit_path(folder.id), :class=>"btn btn-outline btn-primary"%>
              <%= link_to '設為公開', folder.change_status_url('public'), method: :post ,:class=>"btn btn-outline btn-primary" if !folder.is_public %>
              <%= link_to '設為僅由連結公開', folder.change_status_url('link_open'), method: :post,:class=>"btn btn-outline btn-primary"  if !folder.is_link_open %>
              <%= link_to '設為不公開', folder.change_status_url('private'), method: :post ,:class=>"btn btn-outline btn-primary" if !folder.is_private %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <!-- /.table-responsive -->
  </div>